[package]
name = "rev-studio-python"
version = "0.1.0"
authors = ["Solly <solly.ucko@gmail.com>"]
edition = "2018"

[dependencies]
pyo3 = "0.9"
bitfield = "0.13"

[dependencies.rev-studio-interface]
path = '../../rev-studio-interface'
